import React from 'react';
import { Link } from 'react-router-dom';

export function UserGuide({ t }) {
  return (
    <div className="page-user-guide">
      <h1>{t.navUserGuide || "User Guide & Frequently Asked Questions (FAQ)"}</h1>

      <div className="panel-white">
        <h2 style={{ marginTop: 0 }}>Operational Guide for Procurement Officers</h2>
        <p>
          This guide outlines the standard operating procedure for discovering, evaluating, and applying Indian Standards (IS) and Quality Control Orders (QCO) during the preparation of public procurement tender notices under GFR 2017 Rule 144.
        </p>

        <h3 style={{ marginTop: '16px' }}>1. Preparing Your Query</h3>
        <p>
          Procurement officers should avoid quoting manufacturer trade names (e.g. "Tata Tiscon" or "UltraTech Super"). Instead, input the generic engineering material, design grade, chemical requirements, and intended physical application.
        </p>

        <h3>2. Interpreting Recommendation Output</h3>
        <ul style={{ paddingLeft: '20px', lineHeight: '1.7' }}>
          <li>
            <strong>Primary Standards:</strong> Direct specifications covering product characteristics, dimensioning, tolerances, and composition.
          </li>
          <li>
            <strong>Allied Standards:</strong> Mandatory test methods (physical and chemical), sampling procedures, packaging codes, and occupational safety codes that must be referenced to ensure fair tender inspection.
          </li>
          <li>
            <strong>Mandatory Certifications:</strong> Notifications issued by line Ministries (e.g. DPIIT, MeitY, MoHUA) under Section 16 of the BIS Act, 2016 making BIS certification compulsory prior to marketing, sale, or distribution.
          </li>
        </ul>

        <h3>3. Superseded & Withdrawn Standards</h3>
        <p>
          When an older standard is detected in your query or tender document, the engine issues a warning box. Older standards (e.g. IS 8112:1989 for 43 grade cement) must be updated to current amalgamated revisions (e.g. IS 269:2015) to avoid bidder disqualification litigations.
        </p>
      </div>

      {/* Plain FAQ List */}
      <div className="panel">
        <h2 style={{ marginTop: 0 }}>Frequently Asked Questions (FAQ)</h2>

        <div style={{ marginBottom: '16px' }}>
          <h3 style={{ fontSize: '1.05rem', color: 'var(--color-navy)' }}>
            Q1: Is it mandatory for government tenders in India to specify Indian Standards?
          </h3>
          <p>
            Yes. Rule 144(i) of the General Financial Rules (GFR), 2017 mandates that technical specifications should, to the extent practicable, be based on the national standards published by the Bureau of Indian Standards (BIS).
          </p>
        </div>

        <div style={{ marginBottom: '16px' }}>
          <h3 style={{ fontSize: '1.05rem', color: 'var(--color-navy)' }}>
            Q2: What is the legal difference between Scheme-I (ISI Mark) and Scheme-II (CRS)?
          </h3>
          <p>
            Scheme-I involves factory inspection, continuous quality surveillance, and grant of standard ISI mark certification. Scheme-II (Compulsory Registration Scheme) operates on self-declaration of conformity based on laboratory test reports from BIS-recognized labs, primarily for electronic and IT equipment notified by MeitY.
          </p>
        </div>

        <div style={{ marginBottom: '16px' }}>
          <h3 style={{ fontSize: '1.05rem', color: 'var(--color-navy)' }}>
            Q3: Are recommendations made by this portal legally binding?
          </h3>
          <p>
            No. The recommendations generated by this portal are advisory. Tendering authorities must confirm that the standard is current, active, and applicable by checking the official BIS e-Sale portal before issuing tenders.
          </p>
        </div>

        <div style={{ marginBottom: '16px' }}>
          <h3 style={{ fontSize: '1.05rem', color: 'var(--color-navy)' }}>
            Q4: What should an officer do if no Indian Standard matches the required product?
          </h3>
          <p>
            In cases where no published Indian Standard exists, procuring entities may reference internationally recognized ISO/IEC standards or formulate objective performance-based specifications in consultation with technical evaluation committees.
          </p>
        </div>

        <div style={{ marginTop: '20px' }}>
          <Link to="/find" className="btn btn-primary">
            Proceed to Find Standards
          </Link>
        </div>
      </div>
    </div>
  );
}
